# Generated by Django 3.2.5 on 2021-07-18 13:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gig_title', models.CharField(max_length=520)),
            ],
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=210)),
                ('price', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='GigManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gig', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mainApp.gig')),
                ('package', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mainApp.package')),
            ],
        ),
        migrations.AddField(
            model_name='gig',
            name='packages',
            field=models.ManyToManyField(through='mainApp.GigManager', to='mainApp.Package'),
        ),
    ]
